services:
  mysql:
    image: mysql:latest
    container_name: platform_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: universidad
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345678"]
      start_period: 5s
      interval: 3s
      retries: 5
      timeout: 60s
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  mongodb:
      image: mongo:latest
      container_name: platform_mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: 12345678
        MONGO_INITDB_DATABASE: universidad
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - app_network
      healthcheck:
        test: ["CMD", "mongosh", "--host", "localhost", "--username", "admin", "--password", "12345678", "--eval", "db.adminCommand('ping')"]
        start_period: 5s
        interval: 3s
        retries: 5
        timeout: 60s

  server:
    build:
      context: ./plataforma-proyecto
      dockerfile: Dockerfile
    container_name: platform_server
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - app_network

  webpage:
    build:
      context: ./pagina-web-proyecto
      dockerfile: Dockerfile
    container_name: platform_webpage
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: platform_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
      - webpage
    networks:
      - app_network

volumes:
  mysql_data:
  mongo_data:

networks:
  app_network:
    driver: bridge
