name: Despliegue en Producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Desplegar en el servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: sima.uis.edu.co
          username: administrador  # O el usuario que uses para conectarte
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd C:\Proyectos\plataforma-web-proyecto
            git pull origin main
            docker-compose -f plataforma.yml down
            docker-compose -f plataforma.yml up -d --build
