# name: Prueba del runner local

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   test-runner:
#     runs-on: self-hosted  # Esto indica que se usará tu runner en Windows Server

#     steps:
#       - name: Verificar que el runner está activo
#         run: echo "¡Runner ejecutándose correctamente en $env:COMPUTERNAME!"

#       - name: Mostrar fecha y usuario actual
#         run: |
#           echo Fecha: (Get-Date)
#           whoami

#       - name: Verificar ubicación y espacio en disco
#         run: |
#           Get-Location
#           Get-PSDrive C

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # setup:
  #   name: Instalando dependencias
  #   runs-on: self-hosted
  #   steps:
  #     - name: Clonar repositorio
  #       uses: actions/checkout@v3

  #     - name: Configurar Node.js
  #       uses: actions/setup-node@v3

  #     - name: Instalar dependencias
  #       run: |
  #         cd pagina-web-proyecto
  #         yarn install --no-audit --no-fund --no-optional

      # - name: Ejecutar lint
      #   run: |
      #     cd pagina-web-proyecto
      #     yarn lint || true  # Si no quieres que falle por errores de lint

      # - name: Construir frontend
      #   run: |
      #     cd pagina-web-proyecto
      #     yarn build
  
  deploy:
    name: Desplegar al servidor
    runs-on: self-hosted
  #  needs: setup
    steps:     
      - name: Mostrar informacion del entorno
        run: |
          echo "Servidor: $env:COMPUTERNAME"
          echo "Fecha: $(Get-Date)"
          whoami

      - name: Ir al proyecto
        working-directory: 'C:\Proyectos\plataforma-web-proyecto'
        run: echo "Directorio correcto"

      - name: Hacer git pull
        working-directory: 'C:\Proyectos\plataforma-web-proyecto'
        run: |
          git reset --hard
          git pull origin main

      - name: Reconstruir y levantar contenedores Docker con plataforma.yml
        working-directory: 'C:\Proyectos\plataforma-web-proyecto'
        run: |
          docker-compose -f plataforma.yml down
          docker-compose -f plataforma.yml build
          docker-compose -f plataforma.yml up -d

      - name: Ver contenedores en ejecución
        run: docker ps

      # - name: Clonar repositorio
      #   uses: actions/checkout@v3

      # - name: Desplegar en el servidor
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: sima.uis.edu.co
      #     username: administrador
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd C:\Proyectos\plataforma-web-proyecto
      #       git pull origin main
      #       docker-compose -f plataforma.yml down
      #       docker-compose -f plataforma.yml up -d --build
