name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Instalación de dependencias
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3

      - name: Instalar dependencias
        run: |
          cd pagina-web-proyecto
          yarn install --no-audit --no-fund --no-optional

      # - name: Ejecutar lint
      #   run: |
      #     cd pagina-web-proyecto
      #     yarn lint || true  # Si no quieres que falle por errores de lint

      # - name: Construir frontend
      #   run: |
      #     cd pagina-web-proyecto
      #     yarn build
  
  deploy:
    name: Desplegar al servidor
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Obtener clave SSH y ajustar permisos
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          echo "Conectando a IP: ${{ secrets.SERVER_IP }}"
       #   ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Desplegar usando SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -r 
      # - name: Desplegar en el servidor usando SCP
      #   run: |
      #     ssh administrador@${{ secrets.SERVER_IP }} << 'EOF'
      #       cd /c/Proyectos/plataforma-web-proyecto
      #       git pull origin main
      #       docker-compose -f plataforma.yml down
      #       docker-compose -f plataforma.yml up -d --build
      #     EOF

      # - name: Desplegar en el servidor
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: sima.uis.edu.co
      #     username: administrador
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd C:\Proyectos\plataforma-web-proyecto
      #       git pull origin main
      #       docker-compose -f plataforma.yml down
      #       docker-compose -f plataforma.yml up -d --build
