name: Despliegue en Producción

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
  # deploy:
  #   runs-on: ubuntu-latest

    steps:
      - name: Echo the message
        run: |
          echo "Hola Paula!"
      - name: Dime la fecha
        run: date
      - run: ls -l

    # steps:
    #   - name: Clonar repositorio
    #     uses: actions/checkout@v3

      # - name: Desplegar en el servidor
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: sima.uis.edu.co
      #     username: administrador
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd C:\Proyectos\plataforma-web-proyecto
      #       git pull origin main
      #       docker-compose -f plataforma.yml down
      #       docker-compose -f plataforma.yml up -d --build
